# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [jude, wiki]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username sandbox.love
ko_fi: # Replace with a single Ko-fi username mouse3687
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username chime
issuehunt: # Replace with a single IssueHunt username mafia
otechie: # Replace with a single Otechie username Lincoln
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://mad.org','https://pornhub.com','https://javaee.github.io/glassfish/','https://eji.org','https://www.mapquest.com/us/mississippi/lucky-7-tattoos-406845716',']
